//
// Generated file, do not edit! Created by nedtool 4.6 from src/node/communication/routing/gpsrRouting/GpsrRoutingPacket.msg.
//

#ifndef _GPSRROUTINGPACKET_M_H_
#define _GPSRROUTINGPACKET_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include "RoutingPacket_m.h"
// }}

/**
 * Enum generated from <tt>src/node/communication/routing/gpsrRouting/GpsrRoutingPacket.msg:22</tt> by nedtool.
 * <pre>
 * enum GpsrPacketDef
 * {
 * 
 *     GPSR_DATA_PACKET = 0;       // data packet
 *     GPSR_HELLO_MSG_PACKET = 1;      // hello msg
 *     GPSR_REP_HELLO_MSG_PACKET = 2;     // rep hello msg 
 *     GPSR_SINK_ADDRESS_PACKET = 3;    // sink address
 * }
 * </pre>
 */
enum GpsrPacketDef {
    GPSR_DATA_PACKET = 0,
    GPSR_HELLO_MSG_PACKET = 1,
    GPSR_REP_HELLO_MSG_PACKET = 2,
    GPSR_SINK_ADDRESS_PACKET = 3
};

/**
 * Class generated from <tt>src/node/communication/routing/gpsrRouting/GpsrRoutingPacket.msg:30</tt> by nedtool.
 * <pre>
 * packet GpsrPacket extends RoutingPacket
 * {
 *     int GpsrPacketKind @enum(GpsrPacketDef);
 *     int x_src;
 *     int y_src;
 *     int x_dst;	// for the sink when it is a data message
 *     int y_dst;
 * }
 * </pre>
 */
class GpsrPacket : public ::RoutingPacket
{
  protected:
    int GpsrPacketKind_var;
    int x_src_var;
    int y_src_var;
    int x_dst_var;
    int y_dst_var;

  private:
    void copy(const GpsrPacket& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const GpsrPacket&);

  public:
    GpsrPacket(const char *name=NULL, int kind=0);
    GpsrPacket(const GpsrPacket& other);
    virtual ~GpsrPacket();
    GpsrPacket& operator=(const GpsrPacket& other);
    virtual GpsrPacket *dup() const {return new GpsrPacket(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getGpsrPacketKind() const;
    virtual void setGpsrPacketKind(int GpsrPacketKind);
    virtual int getX_src() const;
    virtual void setX_src(int x_src);
    virtual int getY_src() const;
    virtual void setY_src(int y_src);
    virtual int getX_dst() const;
    virtual void setX_dst(int x_dst);
    virtual int getY_dst() const;
    virtual void setY_dst(int y_dst);
};

inline void doPacking(cCommBuffer *b, GpsrPacket& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, GpsrPacket& obj) {obj.parsimUnpack(b);}


#endif // ifndef _GPSRROUTINGPACKET_M_H_

