//
// Generated file, do not edit! Created by nedtool 4.6 from src/node/communication/routing/boundholeRouting/BHRoutingPacket.msg.
//

#ifndef _BHROUTINGPACKET_M_H_
#define _BHROUTINGPACKET_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include "GeoRoutingPacket_m.h"
#include "VirtualMobilityManager.h"
// }}

/**
 * Enum generated from <tt>src/node/communication/routing/boundholeRouting/BHRoutingPacket.msg:25</tt> by nedtool.
 * <pre>
 * enum BoundHoleForwardingMode
 * {
 * 
 *     BOUNDHOLE_GREEDY_ROUTING = 0;
 *     BOUNDHOLE_BOUNDHOLE_ROUTING = 1;
 * }
 * </pre>
 */
enum BoundHoleForwardingMode {
    BOUNDHOLE_GREEDY_ROUTING = 0,
    BOUNDHOLE_BOUNDHOLE_ROUTING = 1
};

/**
 * Class generated from <tt>src/node/communication/routing/boundholeRouting/BHRoutingPacket.msg:30</tt> by nedtool.
 * <pre>
 * packet BHRoutingPacket extends GeoRoutingPacket
 * {
 *     int routingMode = BOUNDHOLE_GREEDY_ROUTING;		// M
 *     NodeLocation_type destinationLocation;		// D
 *     NodeLocation_type startBoundHoleLocation;	// Lp
 *     int holeId = -1;
 *     int originalId = -1;
 *     int startIndex = -1;	// index of node when start boundhole message
 *     int curIndex = -1;			// current index in boundhole
 *     bool direction = true;	// turn right (up)
 * }
 * </pre>
 */
class BHRoutingPacket : public ::GeoRoutingPacket
{
  protected:
    int routingMode_var;
    NodeLocation_type destinationLocation_var;
    NodeLocation_type startBoundHoleLocation_var;
    int holeId_var;
    int originalId_var;
    int startIndex_var;
    int curIndex_var;
    bool direction_var;

  private:
    void copy(const BHRoutingPacket& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const BHRoutingPacket&);

  public:
    BHRoutingPacket(const char *name=NULL, int kind=0);
    BHRoutingPacket(const BHRoutingPacket& other);
    virtual ~BHRoutingPacket();
    BHRoutingPacket& operator=(const BHRoutingPacket& other);
    virtual BHRoutingPacket *dup() const {return new BHRoutingPacket(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getRoutingMode() const;
    virtual void setRoutingMode(int routingMode);
    virtual NodeLocation_type& getDestinationLocation();
    virtual const NodeLocation_type& getDestinationLocation() const {return const_cast<BHRoutingPacket*>(this)->getDestinationLocation();}
    virtual void setDestinationLocation(const NodeLocation_type& destinationLocation);
    virtual NodeLocation_type& getStartBoundHoleLocation();
    virtual const NodeLocation_type& getStartBoundHoleLocation() const {return const_cast<BHRoutingPacket*>(this)->getStartBoundHoleLocation();}
    virtual void setStartBoundHoleLocation(const NodeLocation_type& startBoundHoleLocation);
    virtual int getHoleId() const;
    virtual void setHoleId(int holeId);
    virtual int getOriginalId() const;
    virtual void setOriginalId(int originalId);
    virtual int getStartIndex() const;
    virtual void setStartIndex(int startIndex);
    virtual int getCurIndex() const;
    virtual void setCurIndex(int curIndex);
    virtual bool getDirection() const;
    virtual void setDirection(bool direction);
};

inline void doPacking(cCommBuffer *b, BHRoutingPacket& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, BHRoutingPacket& obj) {obj.parsimUnpack(b);}


#endif // ifndef _BHROUTINGPACKET_M_H_

