//
// Generated file, do not edit! Created by nedtool 4.6 from src/node/application/routingTest/GeoApplicationPacket.msg.
//

#ifndef _GEOAPPLICATIONPACKET_M_H_
#define _GEOAPPLICATIONPACKET_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include "ApplicationPacket_m.h"
#include "VirtualMobilityManager.h"
// }}

/**
 * Class generated from <tt>src/node/application/routingTest/GeoApplicationPacket.msg:28</tt> by nedtool.
 * <pre>
 * packet GeoApplicationPacket extends ApplicationPacket
 * {
 *     NodeLocation_type destinationLocation;
 * }
 * </pre>
 */
class GeoApplicationPacket : public ::ApplicationPacket
{
  protected:
    NodeLocation_type destinationLocation_var;

  private:
    void copy(const GeoApplicationPacket& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const GeoApplicationPacket&);

  public:
    GeoApplicationPacket(const char *name=NULL, int kind=0);
    GeoApplicationPacket(const GeoApplicationPacket& other);
    virtual ~GeoApplicationPacket();
    GeoApplicationPacket& operator=(const GeoApplicationPacket& other);
    virtual GeoApplicationPacket *dup() const {return new GeoApplicationPacket(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual NodeLocation_type& getDestinationLocation();
    virtual const NodeLocation_type& getDestinationLocation() const {return const_cast<GeoApplicationPacket*>(this)->getDestinationLocation();}
    virtual void setDestinationLocation(const NodeLocation_type& destinationLocation);
};

inline void doPacking(cCommBuffer *b, GeoApplicationPacket& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, GeoApplicationPacket& obj) {obj.parsimUnpack(b);}


#endif // ifndef _GEOAPPLICATIONPACKET_M_H_

