//
// Generated file, do not edit! Created by nedtool 4.6 from src/node/communication/routing/geoRouting/protocol/GPSR/GPSRPacket.msg.
//

#ifndef _GPSRPACKET_M_H_
#define _GPSRPACKET_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include "GeoRoutingPacket_m.h"
#include "VirtualMobilityManager.h"
// }}

/**
 * Enum generated from <tt>src/node/communication/routing/geoRouting/protocol/GPSR/GPSRPacket.msg:25</tt> by nedtool.
 * <pre>
 * enum GPSRForwardingMode
 * {
 * 
 *     GPSR_GREEDY_ROUTING = 0;
 *     GPSR_PERIMETER_ROUTING = 1;
 * }
 * </pre>
 */
enum GPSRForwardingMode {
    GPSR_GREEDY_ROUTING = 0,
    GPSR_PERIMETER_ROUTING = 1
};

/**
 * Class generated from <tt>src/node/communication/routing/geoRouting/protocol/GPSR/GPSRPacket.msg:30</tt> by nedtool.
 * <pre>
 * packet GPSRPacket extends GeoRoutingPacket
 * {
 *     int routingMode = GPSR_GREEDY_ROUTING;		// M
 *     NodeLocation_type destinationLocation;		// D	- destination has beed defined in GeoRoutingPacket, let this to clear GPSR packet definition
 *     NodeLocation_type startPerimeterLocation;	// Lp
 *     NodeLocation_type forwardPerimeterLocation;	// Lf
 *     string firstSenderAddress;					// e0
 *     string firstReceiverAddress;				// e0
 *     string senderAddress;
 * }
 * </pre>
 */
class GPSRPacket : public ::GeoRoutingPacket
{
  protected:
    int routingMode_var;
    NodeLocation_type destinationLocation_var;
    NodeLocation_type startPerimeterLocation_var;
    NodeLocation_type forwardPerimeterLocation_var;
    opp_string firstSenderAddress_var;
    opp_string firstReceiverAddress_var;
    opp_string senderAddress_var;

  private:
    void copy(const GPSRPacket& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const GPSRPacket&);

  public:
    GPSRPacket(const char *name=NULL, int kind=0);
    GPSRPacket(const GPSRPacket& other);
    virtual ~GPSRPacket();
    GPSRPacket& operator=(const GPSRPacket& other);
    virtual GPSRPacket *dup() const {return new GPSRPacket(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getRoutingMode() const;
    virtual void setRoutingMode(int routingMode);
    virtual NodeLocation_type& getDestinationLocation();
    virtual const NodeLocation_type& getDestinationLocation() const {return const_cast<GPSRPacket*>(this)->getDestinationLocation();}
    virtual void setDestinationLocation(const NodeLocation_type& destinationLocation);
    virtual NodeLocation_type& getStartPerimeterLocation();
    virtual const NodeLocation_type& getStartPerimeterLocation() const {return const_cast<GPSRPacket*>(this)->getStartPerimeterLocation();}
    virtual void setStartPerimeterLocation(const NodeLocation_type& startPerimeterLocation);
    virtual NodeLocation_type& getForwardPerimeterLocation();
    virtual const NodeLocation_type& getForwardPerimeterLocation() const {return const_cast<GPSRPacket*>(this)->getForwardPerimeterLocation();}
    virtual void setForwardPerimeterLocation(const NodeLocation_type& forwardPerimeterLocation);
    virtual const char * getFirstSenderAddress() const;
    virtual void setFirstSenderAddress(const char * firstSenderAddress);
    virtual const char * getFirstReceiverAddress() const;
    virtual void setFirstReceiverAddress(const char * firstReceiverAddress);
    virtual const char * getSenderAddress() const;
    virtual void setSenderAddress(const char * senderAddress);
};

inline void doPacking(cCommBuffer *b, GPSRPacket& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, GPSRPacket& obj) {obj.parsimUnpack(b);}


#endif // ifndef _GPSRPACKET_M_H_

