//
// Generated file, do not edit! Created by nedtool 4.6 from src/node/communication/routing/geoRouting/GeoControlPacket.msg.
//

#ifndef _GEOCONTROLPACKET_M_H_
#define _GEOCONTROLPACKET_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include "GeoPacket_m.h"
#include "VirtualMobilityManager.h"
// }}

/**
 * Class generated from <tt>src/node/communication/routing/geoRouting/GeoControlPacket.msg:29</tt> by nedtool.
 * <pre>
 * //
 * packet GeoControlPacket extends GeoPacket
 * {
 *     int geoPacketType = GEO_CONTROL_PACKET;
 * 
 * 	// for control parameters
 * }
 * </pre>
 */
class GeoControlPacket : public ::GeoPacket
{
  protected:
    int geoPacketType_var;

  private:
    void copy(const GeoControlPacket& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const GeoControlPacket&);

  public:
    GeoControlPacket(const char *name=NULL, int kind=0);
    GeoControlPacket(const GeoControlPacket& other);
    virtual ~GeoControlPacket();
    GeoControlPacket& operator=(const GeoControlPacket& other);
    virtual GeoControlPacket *dup() const {return new GeoControlPacket(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getGeoPacketType() const;
    virtual void setGeoPacketType(int geoPacketType);
};

inline void doPacking(cCommBuffer *b, GeoControlPacket& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, GeoControlPacket& obj) {obj.parsimUnpack(b);}


#endif // ifndef _GEOCONTROLPACKET_M_H_

