//
// Generated file, do not edit! Created by nedtool 4.6 from src/node/communication/routing/geoRouting/GeoRoutingPacket.msg.
//

#ifndef _GEOROUTINGPACKET_M_H_
#define _GEOROUTINGPACKET_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include "GeoPacket_m.h"
#include "VirtualMobilityManager.h"
// }}

/**
 * Class generated from <tt>src/node/communication/routing/geoRouting/GeoRoutingPacket.msg:28</tt> by nedtool.
 * <pre>
 * packet GeoRoutingPacket extends GeoPacket
 * {
 *     int geoPacketType = GEO_ROUTING_PACKET;
 *     NodeLocation_type destinationLocation;
 * }
 * </pre>
 */
class GeoRoutingPacket : public ::GeoPacket
{
  protected:
    int geoPacketType_var;
    NodeLocation_type destinationLocation_var;

  private:
    void copy(const GeoRoutingPacket& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const GeoRoutingPacket&);

  public:
    GeoRoutingPacket(const char *name=NULL, int kind=0);
    GeoRoutingPacket(const GeoRoutingPacket& other);
    virtual ~GeoRoutingPacket();
    GeoRoutingPacket& operator=(const GeoRoutingPacket& other);
    virtual GeoRoutingPacket *dup() const {return new GeoRoutingPacket(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getGeoPacketType() const;
    virtual void setGeoPacketType(int geoPacketType);
    virtual NodeLocation_type& getDestinationLocation();
    virtual const NodeLocation_type& getDestinationLocation() const {return const_cast<GeoRoutingPacket*>(this)->getDestinationLocation();}
    virtual void setDestinationLocation(const NodeLocation_type& destinationLocation);
};

inline void doPacking(cCommBuffer *b, GeoRoutingPacket& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, GeoRoutingPacket& obj) {obj.parsimUnpack(b);}


#endif // ifndef _GEOROUTINGPACKET_M_H_

